#!/bin/bash

user=root
pass=root
host=127.0.0.1
port=3306
db=sysbench
rows=10000000
tables=8
time=300
lua=/usr/share/sysbench/oltp_point_select.lua
jemalloc=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

function run
	{
  	LD_PRELOAD=$jemalloc sysbench $lua --db-driver=mysql \
   	--table-size=$rows --tables=$tables --threads=$1 --time=$2 \
  	--rate=0 --report-interval=1 --rand-type=uniform  --rand-seed=1  \
  	--mysql-user=$user --mysql-password=$pass --mysql-socket=/run/mysqld/mysqld.sock --mysql-db=$db \
  	--events=0 $3 $4 $5 run
	}

function warmup
	{
 	printf "\nPERFORMING WARMUP\n"
	run 512 $time 
	}

ulimit -n 10000

printf "\nWITHOUT SYSBENCH DYNIMIZED\n"
cp /etc/dyni.conf.mysqld /etc/dyni.conf
service mysql restart
( sleep 100 ; dyni -start ) &
( sleep 300 ; dyni -stop ) &
run 512 600

printf "\nWITH SYSBENCH DYNIMIZED\n"
cp /etc/dyni.conf.sysbench /etc/dyni.conf
service mysql restart
( sleep 100 ; dyni -start ) &
( sleep 300 ; dyni -stop ) &
run 512 600

printf "\nTESTS COMPLETE\n"



