#!/bin/bash

user=root
pass=root
host=127.0.0.1
port=3306
db=sysbench
rows=10000000
tables=8
lua=/usr/share/sysbench/oltp_point_select.lua
jemalloc=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

function prep
	{
	service mysql restart
	mysql -u $user -h $host --password=$pass -e "DROP DATABASE sysbench;"
	mysql -u $user -h $host --password=$pass -e "CREATE DATABASE sysbench;"

  	sysbench $lua --db-driver=mysql \
  	--mysql-storage-engine=InnoDB  --table-size=$rows --tables=$tables \
  	--mysql-user=$user --mysql-password=$pass --mysql-host=$host --mysql-port=$port --mysql-db=$db \
  	--events=0 --threads=8 prepare
	}

prep


